image: docker:latest

stages:
  - build
  - test

build:
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

test:
  stage: test
  services:
    - docker:dind
  before_script:
    - apk add curl
  script:
    - docker run -d --name hustoj -p 8080:80 $CI_REGISTRY_IMAGE
    - sleep 5
    - curl localhost:8080