language: minimal

services:
  - docker

if: tag IS present

before_install:
- docker pull woodenfish42/hustoj-deb-debian8
- docker pull woodenfish42/hustoj-deb-ubuntu18

script:
- docker run -v `pwd`/deb:/tmp/deb woodenfish42/hustoj-deb-debian8 sh -c "DISTRIBUTION=debian8 /root/build.sh"
- docker run -v `pwd`/deb:/tmp/deb woodenfish42/hustoj-deb-ubuntu18 sh -c "DISTRIBUTION=ubuntu18 /root/build.sh"

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: deb/*
  skip_cleanup: true
  on:
    tags: true
